version: 2
jobs:
  build:
    docker:
      - image: "node"
    steps:
      - checkout

      - restore_cache:
          keys:
            - npmdeps-v1-{{ arch }}-{{ checksum "package.json" }}
            - npmdeps-v1-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: npmdeps-v1-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules/"
            - "yarn.lock"

      # Maybe do a restore_cache for bower_components here?
      - run:
          name: Install bower components
          command: node_modules/bower/bin/bower --allow-root install

      - run:
          name: Build polymer project
          command: node_modules/polymer-cli/bin/polymer.js build
      - store_artifacts:
          path: "build"

      - run:
          name: Prepare for deployment
          working_directory: "build/default"
          command: |
            git config --global user.email "$CIRCLE_BUILD_URL"
            git config --global user.name "CircleCI"
            git init
            git remote add --fetch origin "`git --git-dir=../../.git config remote.origin.url`"
            if git rev-parse --verify origin/master > /dev/null 2>&1; then
              git symbolic-ref HEAD refs/heads/master
              git reset
            else
              echo "Creating orphan branch master..."
              git checkout --orphan master
            fi
      - deploy:
          name: Deploy to master
          working_directory: "build/default"
          command: |
            git add -A
            git commit --allow-empty -m "Automated CI deployment [$CIRCLE_BRANCH: $CIRCLE_SHA1]"
            git push --force origin master
